version: '3.6'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - 4cat_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile_backend
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - DB_PORT=${DB_PORT}
    container_name: 4cat_backend
    depends_on:
      - db
    ports:
      - 4444:4444
    command: ${POSTGRES_DB} ${POSTGRES_USER}
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile_frontend
    container_name: 4cat_frontend
    depends_on:
      - db
      - backend
    ports:
      - 443:443
      - 5000:5000
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

volumes:
  4cat_db: {}
  4cat_data: {}
  4cat_share: {}
