version: '3.6'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fourcat
      POSTGRES_PASSWORD: supers3cr3t
      POSTGRES_DB: fourcat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 4cat_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile_backend
    container_name: 4cat_backend
    depends_on:
      - db
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile_frontend
    container_name: 4cat_frontend
    depends_on:
      - db
      - backend
    ports:
      - 5000:5000
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

volumes:
  4cat_db: {}
  4cat_data: {}
  4cat_share: {}
