version: '3.6'

services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - 4cat_db:/var/lib/postgresql/data/

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile_backend
    container_name: 4cat_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${PUBLIC_API_PORT}:4444
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile_frontend
    container_name: 4cat_frontend
    depends_on:
      - db
      - backend
    ports:
      - ${TELEGRAM_PORT}:443
      - ${PUBLIC_PORT}:5000
    volumes:
      - 4cat_data:/usr/src/app/data/
      - 4cat_share:/usr/src/app/docker/shared/

volumes:
  4cat_db: {}
  4cat_data: {}
  4cat_share: {}
